cc_library(
    name = 'quotation_race_client',
    srcs = [
        'race_client_factory_impl.cpp',
        'race_client_factory.cpp',
        'race_client_impl.cpp',
        'race_cluster_config_base.cpp',
        'race_cluster_group_config.cpp',
    ],
    deps = [
       '//quotation_common/quotation/race/common:quotation_race_common'
    ],
    export_incs = [
        '.',
    ]
)