apiVersion: v1
kind: List
items:
- kind: DeploymentConfig
  apiVersion: v1
  metadata: 
    name: "ses-es-0"
    annotations: 
      description: "Defines how to deploy the application server"
      template.alpha.openshift.io/wait-for-ready: "true"
  spec: 
    strategy: 
      type: Recreate
    triggers: 
    - type: ImageChange
      imageChangeParams: 
        automatic: true
        containerNames: 
        - esunny-access
        from:
          kind: ImageStreamTag
          name: "esunny-access:latest"
    - type: ConfigChange
    replicas: 1
    selector: 
      name: "ses-es-0"
    template: 
      metadata:
        name: "ses-es-0"
        labels:
          name: "ses-es-0"
      spec:
        hostIPC: true
        nodeSelector:
          node-role.xueqiao.quotation/access: 'true'
        tolerations:
        - key: "xueqiao.quotation.access"
          operator: "Equal"
          value: "true"
          effect: "NoExecute"
        volumes:
        - hostPath:
            path: /usr/local/soldier/qconf_agent/script
            type: Directory
          name: qconf-scripts
        - hostPath:
            path: /data/configs/qconf
            type: Directory
          name: qconf-configs
        containers: 
        - name: esunny-access
          image: " "
          env:
          - name: APPLOG_STDOUT_MODE
            value: 'true'
          - name: ACCOUNT_ID
            value: '1244'
          - name: PLATFORM
            value: 'SES'
          - name: USER_NAME
            value: 'ES'
          - name: USER_PASSWD
            value: '123456'
          - name: AUTH_CODE
            value: 'B112F916FE7D27BCE7B97EB620206457946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC946CED32E26C1EAC5211AF9FEE541DDE9D6F622F72E25D5DEF7F47AA93A738EF5A51B81D8526AB6A9D19E65B41F59D6A946CED32E26C1EACCAF8D4C61E28E2B1ABD9B8F170E14F8847D3EA0BF4E191F5DCB1B791E63DC196D1576DEAF5EC563CA3E560313C0C3411B45076795F550EB050A62C4F74D5892D2D14892E812723FAC858DEBD8D4AF9410729FB849D5D8D6EA48A1B8DC67E037381A279CE9426070929D5DA085659772E24A6F5EA52CF92A4D403F9E46083F27B19A88AD99812DADA44100324759F9FD1964EBD4F2F0FB50B51CD31C0B02BB437'
          - name: QUOT_ADDR
            value: '123.161.206.213:7171'
          - name: RESTART_CLOCKS
            value: ''
          - name: HOST_ADDR
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.1"
              memory: "200Mi"
          volumeMounts:
          - mountPath: /usr/local/soldier/qconf_agent/script
            name: qconf-scripts
          - mountPath: /data/configs/qconf
            name: qconf-configs