apiVersion: v1
kind: List
items:
- kind: BuildConfig
  apiVersion: v1
  metadata: 
    name: "esunny-access"
    annotations: 
      description: "Defines how to build esunny-access"
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    nodeSelector:
      node-role.soldier.platform/builder: 'true'
    source: 
      type: "Git"
      git: 
        uri: "ssh://git@git.soldier-tools.svc:29418/xueqiao-quotation/esunny_access.git"
        ref: "dev"
      sourceSecret:
        name: xueqiao-git
    strategy: 
      type: Source
      sourceStrategy: 
        env:
        - name: BUILD_BRANCH
          value: dev
        incremental: true
        from: 
          kind: ImageStreamTag
          namespace: soldier-platform
          name: cpp-platform:latest
    output:
      to:
        kind: ImageStreamTag
        name: "esunny-access:latest"
    triggers: 
    - type: ImageChange
    - type: ConfigChange
    - type: Generic
      generic: 
        secret: "79ksdfuj1sdf8120sdflzsdfpposdlfiwerk1lsdf"