cc_binary(
    name = "group_receivor_test",
    srcs = [
        'group_receivor_test.cpp',
    ],
    deps = [
        '//quotation/subscribe:subscribe_api'
    ]
)

cc_binary(
    name = "subscribe_system_test",
    srcs = [
        'subscribe_system_test.cpp',
    ],
    deps = [
        '//quotation/subscribe:subscribe_api'
    ]
)

cc_binary(
    name = "topic_test",
    srcs = [
        'topic_test.cc',
    ],
    deps = [
        '//quotation/subscribe:subscribe_api'
    ]
)

cc_binary(
    name = "zmq_keepalive_test",
    srcs = [
        'zmq_keepalive_test.cpp',
    ],
    deps = [
        '//quotation/subscribe:subscribe_api'
    ]
)