/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.quotation.query.dao;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum QuotationQueryDaoErrorCode implements org.apache.thrift.TEnum {
  CONTRACT_NOT_FOUND(3001),
  QUERY_LIMITED(3002);

  private final int value;

  private QuotationQueryDaoErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static QuotationQueryDaoErrorCode findByValue(int value) { 
    switch (value) {
      case 3001:
        return CONTRACT_NOT_FOUND;
      case 3002:
        return QUERY_LIMITED;
      default:
        return null;
    }
  }
}
