/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef quotation_item_CONSTANTS_H
#define quotation_item_CONSTANTS_H

#include "../../../buildgen/quotation_common/thrift/quotation_item_types.h"

namespace xueqiao { namespace quotation {

class quotation_itemConstants {
 public:
  quotation_itemConstants();

  std::string PLATFORM_CTP;
  std::string PLATFORM_SIMU_CTP;
  std::string PLATFORM_SP;
  std::string PLATFORM_SIMU_SP;
  std::string PLATFORM_ESUNNY;
  std::string PLATFROM_SIMY_ESUNNY;
  std::string PLATFORM_XUEQIAO;
  std::string PLATFORM_SIMU_XUEQIAO;
};

extern const quotation_itemConstants g_quotation_item_constants;

}} // namespace

#endif
