cc_binary(
    name = 'quotation_process_monitor',
    srcs = [
        'monitor.cpp',
        'accessstate_reporter.cpp',
        'effective_manager.cpp',
        'subprocess_manager.cpp',
    ],
    deps = [
        '//quotation_common/quotation/access/common:access_common',
        '//quotation_common/quotation/access/service:quotation_access_service',
    ]
)