cc_library(
    name = 'quotation_race_common',
    srcs = [
        'group_config.cpp',
    ],
    deps = [
        '//quotation_common/thrift:quotation_thrift',
        '//cpp_platform/attr:soldier_attr',
        '//cpp_platform/inotify:inotifycpp',
        '//cpp_platform/thirdparty/cppzmq:cppzmq',
        '//cpp_platform/thirdparty/rapidjson:rapidjson',
        '//cpp_platform/watcher:file_watcher_module',
    ],
    export_incs = [
        '.',
    ]
)