cc_library(
    name = 'thrift_page',
    srcs = [
        'src/gen/page_constants.cpp',
        'src/gen/page_types.cpp',
    ],
    export_incs = [
        'src/gen',
    ],
    deps = [
        '//cpp_platform/svr:svrcpp',
    ]
)